In [ ]:
import pandas as pd

In [ ]:
import numpy as nm

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('iris.csv')

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df[['sepal_length','sepal_width','petal_length','petal_width']]

In [ ]:
y=df['species']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [ ]:
print(X_train.shape)

(112, 4)


In [ ]:
print(X_test.shape)

(38, 4)


In [ ]:
print(y_train.shape)

(112,)


In [ ]:
print(y_test.shape)

(38,)


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
X_train=sc.fit_transform(X_train)

In [ ]:
X_test=sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
NB=GaussianNB()

In [ ]:
NB.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=NB.predict(X_test)

In [ ]:
print(y_pred)

['versicolor' 'setosa' 'versicolor' 'virginica' 'setosa' 'virginica'
 'virginica' 'setosa' 'setosa' 'virginica' 'setosa' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'setosa' 'setosa'
 'virginica' 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica'
 'setosa' 'virginica' 'virginica' 'versicolor' 'virginica' 'virginica'
 'setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'setosa' 'setosa'
 'versicolor']


In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,classification_report

In [ ]:
cm=confusion_matrix(y_test,y_pred)

In [ ]:
print(cm)

[[14  0  0]
 [ 0 11  0]
 [ 0  0 13]]


In [ ]:
cr=classification_report(y_test,y_pred)

In [ ]:
print(cr)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [ ]:
pr =precision_score(y_test,y_pred,average='micro')

In [ ]:
print(pr)

1.0


In [ ]:
ac=accuracy_score(y_test,y_pred)

In [ ]:
print(ac)

1.0


In [ ]:
rs=recall_score(y_test,y_pred,average='micro')

In [ ]:
print(rs)

1.0


In [ ]:
error_rate=1-ac

In [ ]:
print(error_rate)

0.0
